services:
  
  client:
    image: client
    container_name: client
    ports:
      - "3000:3000"
  
  webapi:
    image: webapi
    container_name: webapi
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - postgres
    command: >
      sh -c "dotnet ef database update --project /src/DataAccess && dotnet WebApiApplication.dll"
  
  
  postgres:
    image: postgres
    container_name: pg
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "database"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
  
  proxy:
    image: nginx
    container_name: proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - webapi
      - client

volumes:
  postgres-data: