services:
  
  client:
    image: client
    container_name: client
    ports:
      - "3000:3000"
  
  webapi:
    image: webapi
    container_name: webapi
    build:
      context: .
      dockerfile: WebApiApplication/Dockerfile
    ports:
      - "5001:80"
      - "5002:443"
    depends_on:
      - data_access
  
  data_access:
    image: data_access
    container_name: data_access
    build:
      context: .
      dockerfile: DataAccess/Dockerfile
    depends_on:
      - postgres
    command: >
      sh -c "dotnet ef database update && dotnet ApiService.dll"
  
  postgres:
    image: postgres
    container_name: pg
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "database"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5555:5432"
  
  proxy:
    image: nginx
    container_name: proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - webapi
      - client

volumes:
  postgres-data:
